linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  revive:
    severity: warning
    rules:
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false
  staticcheck:
    checks: ["all"]


linters:
  enable:
    - errcheck
    - govet
    - gocyclo
    - revive
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-use-default: false
